#include <stdlib.h>
#include "parser.h"
#include "lexer.h"
#include <stdbool.h>
#include <stdio.h>
#include <err.h>
#include "semantic.h"





int main() {
    // Test cases
    char* sourceCode = 
    "ClientProfile Daniel;\n"
    "assign muscleBuildingPlan to Daniel {\n"
    "    Monday {\n"
    "        exercise: \"squats\" | sets: 3 | rest: 1\n"
    "        exercise: \"leg press\" | sets: 3 | rest: 1\n"
    "    }\n"
    "    Tuesday {\n"
    "        exercise: \"bench press\" | sets: 3 | rest: 1\n"
    "    }\n"
    "};";


    // Assuming readSourceCode and lexer are defined and implemented
    Token** tokens;

    // Create symbol table
    struct SymbolTable* table = createSymbolTable();

    // Test case 1
    tokens = lexer(sourceCode);
    //printf("Tokens generated by lexer for Test Case 1:\n");
    //for (int i = 0; tokens[i] != NULL; i++) {
    //    printf("Token %d: type = %d, value = %s\n", i, tokens[i]->type, tokens[i]->value);
    //}
    ASTNode* ast1 = parseProgram(tokens);
    printf("AST generated by parser for Test Case 1:\n");
    if (ast1 == NULL) {
        fprintf(stderr, "Error in parsing Test Case 1.\n");
    } else {
        printAST(ast1, 0);
    }

    printf("Performing semantic analysis for Test Case 1...\n");
    int result = performSemanticAnalysis(ast1, table);
    if (result == 0) {
        printf("No errors found in semantic analysis for Test Case 1.\n");
    } else {
        printf("Errors found in semantic analysis for Test Case 1.\n");
    }

    return EXIT_SUCCESS;
}